# Configuration for XML element fields used in parsing: xml_parser_onto.py

# KG fields configuration: (tag, ontology_property_name, data_type)
KG_FIELDS = [
    ("KG001", "hasDesignation", "xsd:string"),
    ("KG002", "hasAlternativeDesignation", "xsd:string"),
    ("KG101", "hasStreetCode", "xsd:string"),
    ("KG102", "hasStreetName", "xsd:string"),
    ("KG103", "hasDistrictCode", "xsd:string"),
    ("KG104", "hasDistrictName", "xsd:string"),
    ("KG105", "hasMunicipalityCode", "xsd:string"),
    ("KG106", "hasAreaCode", "xsd:string"),
    ("KG107", "hasCatchmentAreaCode", "xsd:string"),
    ("KG108", "hasTreatmentPlantNumber", "xsd:string"),
    ("KG211", "hasDepth", "xsd:float"),
    ("KG301", "hasSewerType", "xsd:string"),
    ("KG302", "hasSewerUsage", "xsd:string"),
    ("KG303", "hasYearOfConstruction", "xsd:integer"),
    ("KG304", "hasMaterial", "xsd:string"),
    ("KG305", "hasNodeType", "xsd:string"),
    ("KG306", "hasNodeStructureType", "xsd:string"),
    ("KG307", "hasNodeShaftShape", "xsd:string"),
    ("KG308", "hasNodeShaftLength", "xsd:integer"),
    ("KG309", "hasNodeShaftWidth", "xsd:integer"),
    ("KG310", "hasNodeCoverShape", "xsd:string"),
    ("KG311", "hasNodeCoverMaterial", "xsd:string"),
    ("KG312", "hasNodeCoverClass", "xsd:string"),
    ("KG313", "hasNodeCoverWidth", "xsd:integer"),
    ("KG314", "hasNodeCoverLength", "xsd:integer"),
    ("KG315", "isNodeCoverBolted", "xsd:boolean"),
    ("KG316", "hasNodeChannelShape", "xsd:string"),
    ("KG317", "hasNodeChannelMaterial", "xsd:string"),
    ("KG318", "hasNodeChannelWidth", "xsd:integer"),
    ("KG319", "hasNodeChannelLength", "xsd:integer"),
    ("KG320", "hasNodeBenchMaterial", "xsd:string"),
    ("KG321", "hasNodeInternalProtection", "xsd:string"),
    ("KG322", "hasNodeInternalProtectionMaterial", "xsd:string"),
    ("KG323", "hasNodeClimbingAid", "xsd:string"),
    ("KG324", "hasNodeNumberOfClimbingIrons", "xsd:integer"),
    ("KG325", "hasNodeClimbingAidMaterial", "xsd:string"),
    ("KG326", "hasNodeMeasurementTechnology", "xsd:string"),
    ("KG401", "hasFunctionalStatus", "xsd:string"),
    ("KG402", "hasOwnership", "xsd:string"),
    ("KG403", "hasWaterProtectionZone", "xsd:string"),
    ("KG404", "hasTrafficArea", "xsd:string"),
    ("KG405", "hasGroundwaterLevel", "xsd:string"),
    ("KG406", "hasFloodArea", "xsd:string"),
    ("KG407", "hasDataStatus", "xsd:string"),
    ("KG408", "hasFloodingFrequency", "xsd:string"),
    ("KG409", "hasSoilGroup", "xsd:string"),
    # ("KG998", "hasDocument", "xsd:string"),
    # ("KG999", "hasRemarks", "xsd:string"),
]


# KA fields configuration: (tag, ontology_property_name, data_type)
KA_FIELDS = [
    ("KA001", "hasNodeStructureComponent", "xsd:string"),
    ("KA002", "hasNodeStructureMaterial", "xsd:string"),
    ("KA003", "hasNodeStructureQuantity", "xsd:integer"),
    ("KA004", "hasNodeStructureHeight", "xsd:float"),
    ("KA005", "hasNodeStructureWidth", "xsd:float"),
    ("KA006", "hasNodeStructureLength", "xsd:float"),
    ("KA007", "hasNodeStructureShape", "xsd:string"),
]


# KI fields configuration: (tag, ontology_property_name, data_type)
KI_FIELDS = [
    ("KI001", "hasClient", "xsd:string"),
    ("KI002", "hasProjectNumber", "xsd:string"),
    ("KI003", "hasInspectionNumber", "xsd:integer"),
    ("KI004", "hasInspectionReason", "xsd:string"),
    ("KI005", "hasCodingSystem", "xsd:string"),
    ("KI006", "hasCameraSystemUsed", "xsd:string"),
    ("KI007", "hasProcessingStatus", "xsd:string"),
    ("KI008", "hasProcessingNote", "xsd:string"),
    ("KI103", "hasInspectionType", "xsd:string"),
    ("KI104", "hasInspectionDateTime", "xsd:string"), # !: Note this should be xsd:dateTime, however it has to be string first and is then converted to dateTime in xml_parerser_onto.py.
    ("KI105", "hasInspectionDateTime", "xsd:string"),  # !: Note this should be xsd:dateTime, however it has to be string first and is then converted to dateTime in xml_parerser_onto.py.
    ("KI106", "hasWeather", "xsd:string"),
    ("KI107", "hasCleaning", "xsd:string"),
    ("KI108", "hasTemperature", "xsd:integer"),
    ("KI109", "hasBackflowPrevention", "xsd:string"),
    ("KI110", "hasWaterLevel", "xsd:integer"),
    ("KI111", "hasCompany", "xsd:string"),
    ("KI112", "hasInspector", "xsd:string"),
    ("KI113", "hasSiteManagement", "xsd:string"),
    ("KI114", "hasVideoStorageMedium", "xsd:string"),
    ("KI115", "hasVideoStorageMediumName", "xsd:string"),
    ("KI116", "hasVideoFilename", "xsd:string"),
    ("KI117", "hasPhotoStorageMedium", "xsd:string"),
    ("KI201", "hasReport", "xsd:string"),
    ("KI202", "hasReportDate", "xsd:dateTime"),
    ("KI203", "hasReporter", "xsd:string"),
    ("KI204", "hasAssessmentDate", "xsd:dateTime"),
    ("KI205", "hasAssessor", "xsd:string"),
    ("KI206", "hasMaximumConditionClassTightness", "xsd:integer"),
    ("KI207", "hasMaximumConditionClassStructuralStability", "xsd:integer"),
    ("KI208", "hasMaximumConditionClassOperationalSafety", "xsd:integer"),
    ("KI209", "hasConditionPointsTightness", "xsd:integer"),
    ("KI210", "hasConditionPointsStructuralStability", "xsd:integer"),
    ("KI211", "hasConditionPointsOperationalSafety", "xsd:integer"),
    ("KI212", "hasEvaluationPointsTightness", "xsd:integer"),
    ("KI213", "hasEvaluationPointsStructuralStability", "xsd:integer"),
    ("KI214", "hasEvaluationPointsOperationalSafety", "xsd:integer"),
    ("KI215", "hasRehabilitationRequirementNumber", "xsd:integer"),
    ("KI216", "hasAssessmentClass", "xsd:integer"),
    ("KI217", "hasPriority", "xsd:integer"),
    ("KI101", "hasNodeInspectionVerticalReferencePoint", "xsd:string"),
    ("KI102", "hasNodeInspectionCircumferentialReferencePoint", "xsd:string"),
    ("KI118", "hasNodeInspectionDigitalPhotoName", "xsd:string"),
    ("KI119", "hasNodeInspectionOperationalSafety", "xsd:boolean"),
    ("KI120", "hasNodeInspectionCorrectCone", "xsd:boolean"),
    ("KI121", "hasNodeInspectionAmbientAir", "xsd:string"),
    ("KI122", "hasNodeInspectionAmbientPhoto", "xsd:string"),
]


# KZ fields configuration: (tag, ontology_property_name, data_type)
KZ_FIELDS = [
    ("KZ001", "hasNodeConditionDepth", "xsd:float"),
    ("KZ002", "hasConditionCode", "xsd:string"),
    ("KZ014", "hasCharacterization1", "xsd:string"),
    ("KZ015", "hasCharacterization2", "xsd:string"),
    ("KZ003", "hasQuantification1", "xsd:float"),
    ("KZ004", "hasQuantification2", "xsd:float"),
    ("KZ005", "hasLinearDamage", "xsd:string"),
    ("KZ006", "hasPositionFrom", "xsd:string"),
    ("KZ007", "hasPositionTo", "xsd:string"),
    ("KZ008", "hasVideoCounterReading", "xsd:string"),
    ("KZ009", "hasImageName", "xsd:string"),
    ("KZ010", "hasLongText", "xsd:string"),
    ("KZ011", "hasConnection", "xsd:string"),
    ("KZ017", "hasStandardizedComment", "xsd:string"),
    ("KZ204", "hasClassificationDate", "xsd:dateTime"),
    ("KZ205", "hasClassifier", "xsd:string"),
    ("KZ206", "hasConditionClassTightness", "xsd:integer"),
    ("KZ207", "hasConditionClassStructuralStability", "xsd:integer"),
    ("KZ208", "hasConditionClassOperationalSafety", "xsd:integer"),
    ("KZ997", "hasCameraSpecificDataPlaceholder", "xsd:string"),
    ("KZ013", "hasNodeConditionShaftArea", "xsd:string"),
    ("KZ016", "hasNodeConditionLocalizedRepair", "xsd:string"),
]



# HG fields configuration: (tag, ontology_property_name or special_key, data_type)
HG_FIELDS = [
    ("HG001", "hasDesignation", "xsd:string"),
    ("HG002", "hasAlternativeDesignation", "xsd:string"),
    ("HG101", "hasStreetCode", "xsd:string"),
    ("HG102", "hasStreetName", "xsd:string"),
    ("HG103", "hasDistrictCode", "xsd:string"),
    ("HG104", "hasDistrictName", "xsd:string"),
    ("HG105", "hasMunicipalityCode", "xsd:string"),
    ("HG106", "hasAreaCode", "xsd:string"),
    ("HG107", "hasCatchmentAreaCode", "xsd:string"),
    ("HG108", "hasTreatmentPlantNumber", "xsd:integer"),
    ("HG301", "hasSewerType", "xsd:string"),
    ("HG302", "hasSewerUsage", "xsd:string"),
    ("HG303", "hasYearOfConstruction", "xsd:integer"),
    ("HG304", "hasMaterial", "xsd:string"),
    ("HG312", "hasDepth", "xsd:float"),
    ("HG401", "hasFunctionalStatus", "xsd:string"),
    ("HG402", "hasOwner", "xsd:string"),
    ("HG403", "hasWaterProtectionZone", "xsd:string"),
    ("HG404", "hasTrafficArea", "xsd:string"),
    ("HG405", "hasGroundwaterLevel", "xsd:string"),
    ("HG406", "hasFloodArea", "xsd:string"),
    ("HG407", "hasDataStatus", "xsd:string"),
    ("HG408", "hasFloodingFrequency", "xsd:string"),
    ("HG409", "hasSoilGroup", "xsd:string"),
    ("HG003", "start_node_designation", "xsd:string"),
    ("HG004", "end_node_designation", "xsd:string"),
    ("HG006", "hasPipeSectionObjectType", "xsd:string"),
    ("HG007", "hasPipeSectionConnectingPipeStationing", "xsd:float"),
    ("HG008", "hasPipeSectionConnectingPipeStationingDirection", "xsd:string"),
    ("HG009", "hasPipeSectionConnectingPipePositioning", "xsd:integer"),
    ("HG010", "hasPipeSectionEndPointType", "xsd:string"),
    ("HG011", "hasPipeSectionPipeLineDesignation", "xsd:string"),
    ("HG012", "isChildOf", "xsd:string"),
    ("HG305", "hasPipeSectionProfileType", "xsd:string"),
    ("HG306", "hasPipeSectionProfileWidth", "xsd:integer"),
    ("HG307", "hasPipeSectionProfileHeight", "xsd:integer"),
    ("HG308", "hasPipeSectionProfileLining", "xsd:string"),
    ("HG309", "hasPipeSectionProfileLiningMaterial", "xsd:string"),
    ("HG310", "hasPipeSectionLength", "xsd:float"),
    ("HG311", "hasPipeSectionGradient", "xsd:float"),
    ("HG313", "hasPipeSectionType", "xsd:string"),
    ("HG314", "hasPipeSectionPipeLength", "xsd:float"),
    ("HG315", "hasPipeSectionStatusProfileDetail", "xsd:string"),
    ("HG316", "hasPipeSectionSelfSupportingLining", "xsd:boolean"),
    ("HG410", "hasPipeSectionWallThickness", "xsd:integer"),
    ("HG411", "hasPipeSectionBeddingType", "xsd:string"),
]

# HI Haltungsinspektionsdaten (tag, dictionary_key, data_type)
HI_FIELDS = [
    ("HI001", "hasClient", "xsd:string"),
    ("HI002", "hasProjectNumber", "xsd:string"),
    ("HI003", "hasInspectionNumber", "xsd:integer"),
    ("HI004", "hasInspectionReason", "xsd:string"),
    ("HI005", "hasCodingSystem", "xsd:string"),
    ("HI006", "hasCameraSystemUsed", "xsd:string"),
    ("HI007", "hasProcessingStatus", "xsd:string"),
    ("HI008", "hasProcessingNote", "xsd:string"),
    ("HI103", "hasInspectionType", "xsd:string"),
    ("HI104", "hasInspectionDateTime", "xsd:string"), # !: Note this should be xsd:dateTime, however it has to be string first and is then converted to dateTime in xml_parerser_onto.py.
    ("HI105", "hasInspectionDateTime", "xsd:string"),  # !: Note this should be xsd:dateTime, however it has to be string first and is then converted to dateTime in xml_parerser_onto.py.
    ("HI106", "hasWeather", "xsd:string"),
    ("HI107", "hasCleaning", "xsd:string"),
    ("HI108", "hasTemperature", "xsd:integer"),
    ("HI109", "hasBackflowPrevention", "xsd:string"),
    ("HI110", "hasWaterLevel", "xsd:integer"),
    ("HI111", "hasCompany", "xsd:string"),
    ("HI112", "hasInspector", "xsd:string"),
    ("HI113", "hasSiteManagement", "xsd:string"),
    ("HI114", "hasVideoStorageMedium", "xsd:string"),
    ("HI115", "hasVideoStorageMediumName", "xsd:string"),
    ("HI116", "hasVideoFilename", "xsd:string"),
    ("HI117", "hasPhotoStorageMedium", "xsd:string"),
    ("HI201", "hasReport", "xsd:string"),
    ("HI202", "hasReportDate", "xsd:dateTime"),
    ("HI203", "hasReporter", "xsd:string"),
    ("HI204", "hasAssessmentDate", "xsd:dateTime"),
    ("HI205", "hasAssessor", "xsd:string"),
    ("HI206", "hasMaximumConditionClassTightness", "xsd:integer"),
    ("HI207", "hasMaximumConditionClassStructuralStability", "xsd:integer"),
    ("HI208", "hasMaximumConditionClassOperationalSafety", "xsd:integer"),
    ("HI209", "hasConditionPointsTightness", "xsd:integer"),
    ("HI210", "hasConditionPointsStructuralStability", "xsd:integer"),
    ("HI211", "hasConditionPointsOperationalSafety", "xsd:integer"),
    ("HI212", "hasEvaluationPointsTightness", "xsd:integer"),
    ("HI213", "hasEvaluationPointsStructuralStability", "xsd:integer"),
    ("HI214", "hasEvaluationPointsOperationalSafety", "xsd:integer"),
    ("HI215", "hasRehabilitationRequirementNumber", "xsd:integer"),
    ("HI216", "hasAssessmentClass", "xsd:integer"),
    ("HI217", "hasPriority", "xsd:integer"),
    ("HI101", "hasPipeSectionInspectionDirection", "xsd:string"),
    ("HI102", "hasPipeSectionInspectionReferencePointStart", "xsd:string"),
]

# HZ Haltungszustandsdaten (tag, dictionary_key, data_type)
HZ_FIELDS = [
    ("HZ001", "hasPipeSectionConditionStation", "xsd:float"),
    ("HZ002", "hasConditionCode", "xsd:string"),
    ("HZ014", "hasCharacterization1", "xsd:string"),
    ("HZ015", "hasCharacterization2", "xsd:string"),
    ("HZ003", "hasQuantification1", "xsd:float"),
    ("HZ004", "hasQuantification2", "xsd:float"),
    ("HZ005", "hasLinearDamage", "xsd:string"),
    ("HZ006", "hasPositionFrom", "xsd:string"),
    ("HZ007", "hasPositionTo", "xsd:string"),
    ("HZ008", "hasVideoCounterReading", "xsd:string"),
    ("HZ009", "hasImageName", "xsd:string"),
    ("HZ010", "hasLongText", "xsd:string"),
    ("HZ011", "hasConnection", "xsd:string"),
    ("HZ017", "hasStandardizedComment", "xsd:string"),
    ("HZ204", "hasClassificationDate", "xsd:dateTime"),
    ("HZ205", "hasClassifier", "xsd:string"),
    ("HZ206", "hasConditionClassTightness", "xsd:integer"),
    ("HZ207", "hasConditionClassStructuralStability", "xsd:integer"),
    ("HZ208", "hasConditionClassOperationalSafety", "xsd:integer"),
    ("HZ997", "hasCameraSpecificDataPlaceholder", "xsd:string"),
    ("HZ012", "hasPipeSectionConditionLining", "xsd:integer"),
    ("HZ016", "hasPipeSectionConditionLocalizedRepair", "xsd:string"),
]

# HM Haltungsmesswertdaten (tag, dictionary_key, data_type)
HM_FIELDS = [
    ("HM001", "hasMeasurementStation", "xsd:float"),
]

# GO fields configuration: (tag, dictionary_key, data_type)
GO_FIELDS = [
    ("GO001", "hasGeometryObjectDesignation", "xsd:string"),
    ("GO002", "hasGeometryObjectIdentifier", "xsd:string"),
    ("GO003", "hasGeometryObjectType", "xsd:string"),
]


# GP fields configuration: (tag, dictionary_key, data_type)
GP_FIELDS = [
    ("GP001", "hasGeometryPointDesignation", "xsd:string"),
    ("GP002", "hasCoordinateSystem", "xsd:string"),
    ("GP003", "hasEasting", "xsd:float"),
    ("GP004", "hasNorthing", "xsd:float"),
    ("GP005", "hasEastCoordinate", "xsd:string"),
    ("GP006", "hasNorthCoordinate", "xsd:string"),
    ("GP007", "hasHeight", "xsd:float"),
    ("GP008", "hasPositionalAccuracy", "xsd:string"),
    ("GP009", "hasElevationAccuracy", "xsd:string"),
    ("GP010", "hasElevationSystem", "xsd:string"),
    ("GP101", "hasPointType", "xsd:string"),
    ("GP102", "hasOrientation", "xsd:string"),
]

# Dictionary to organize all field configurations by element type
FIELDS_CONFIG = {
    'KG': KG_FIELDS,
    'KA': KA_FIELDS,
    'KI': KI_FIELDS,
    'KZ': KZ_FIELDS,
    'HG': HG_FIELDS,
    'HI': HI_FIELDS,
    'HZ': HZ_FIELDS,
    'HM': HM_FIELDS,
    'GO': GO_FIELDS,
    'GP': GP_FIELDS,
}