# Configuration for XML element fields used in parsing: xml_parser_onto.py

# KG fields configuration: (tag, ontology_property_name, data_type)
KG_FIELDS = [
    ("KG001", "hasDesignation", "xsd:string"),
    ("KG002", "hasAlternativeDesignation", "xsd:string"),
    ("KG101", "hasStreetCode", "xsd:string"),
    ("KG102", "hasStreetName", "xsd:string"),
    ("KG103", "hasDistrictCode", "xsd:string"),
    ("KG104", "hasDistrictName", "xsd:string"),
    ("KG105", "hasMunicipalityCode", "xsd:string"),
    ("KG106", "hasAreaCode", "xsd:string"),
    ("KG107", "hasCatchmentAreaCode", "xsd:string"),
    ("KG108", "hasTreatmentPlantNumber", "xsd:string"),
    ("KG211", "hasDepth", "xsd:float"),
    ("KG301", "hasSewerType", "xsd:string"),
    ("KG302", "hasSewerUsage", "xsd:string"),
    ("KG303", "hasYearOfConstruction", "xsd:integer"),
    ("KG304", "hasMaterial", "xsd:string"),
    ("KG305", "hasNodeType", "xsd:string"),
    ("KG306", "hasNodeStructureType", "xsd:string"),
    ("KG307", "hasNodeShaftShape", "xsd:string"),
    ("KG308", "hasNodeShaftLength", "xsd:integer"),
    ("KG309", "hasNodeShaftWidth", "xsd:integer"),
    ("KG310", "hasNodeCoverShape", "xsd:string"),
    ("KG311", "hasNodeCoverMaterial", "xsd:string"),
    ("KG312", "hasNodeCoverClass", "xsd:string"),
    ("KG313", "hasNodeCoverWidth", "xsd:integer"),
    ("KG314", "hasNodeCoverLength", "xsd:integer"),
    ("KG315", "isNodeCoverBolted", "xsd:boolean"),
    ("KG316", "hasNodeChannelShape", "xsd:string"),
    ("KG317", "hasNodeChannelMaterial", "xsd:string"),
    ("KG318", "hasNodeChannelWidth", "xsd:integer"),
    ("KG319", "hasNodeChannelLength", "xsd:integer"),
    ("KG320", "hasNodeBenchMaterial", "xsd:string"),
    ("KG321", "hasNodeInternalProtection", "xsd:string"),
    ("KG322", "hasNodeInternalProtectionMaterial", "xsd:string"),
    ("KG323", "hasNodeClimbingAid", "xsd:string"),
    ("KG324", "hasNodeNumberOfClimbingIrons", "xsd:integer"),
    ("KG325", "hasNodeClimbingAidMaterial", "xsd:string"),
    ("KG326", "hasNodeMeasurementTechnology", "xsd:string"),
    ("KG401", "hasFunctionalStatus", "xsd:string"),
    ("KG402", "hasOwnership", "xsd:string"),
    ("KG403", "hasWaterProtectionZone", "xsd:string"),
    ("KG404", "hasTrafficArea", "xsd:string"),
    ("KG405", "hasGroundwaterLevel", "xsd:string"),
    ("KG406", "hasFloodArea", "xsd:string"),
    ("KG407", "hasDataStatus", "xsd:string"),
    ("KG408", "hasFloodingFrequency", "xsd:string"),
    ("KG409", "hasSoilGroup", "xsd:string"),
    # ("KG998", "hasDocument", "xsd:string"),
    # ("KG999", "hasRemarks", "xsd:string"),
]

# HG fields configuration: (tag, ontology_property_name or special_key, data_type)
HG_FIELDS = [
    ("HG001", "hasDesignation", "xsd:string"),
    ("HG002", "hasAlternativeDesignation", "xsd:string"),
    ("HG101", "hasStreetCode", "xsd:string"),
    ("HG102", "hasStreetName", "xsd:string"),
    ("HG103", "hasDistrictCode", "xsd:string"),
    ("HG104", "hasDistrictName", "xsd:string"),
    ("HG105", "hasMunicipalityCode", "xsd:string"),
    ("HG106", "hasAreaCode", "xsd:string"),
    ("HG107", "hasCatchmentAreaCode", "xsd:string"),
    ("HG108", "hasTreatmentPlantNumber", "xsd:integer"),
    ("HG301", "hasSewerType", "xsd:string"),
    ("HG302", "hasSewerUsage", "xsd:string"),
    ("HG303", "hasYearOfConstruction", "xsd:integer"),
    ("HG304", "hasMaterial", "xsd:string"),
    ("HG312", "hasDepth", "xsd:float"),
    ("HG401", "hasFunctionalStatus", "xsd:string"),
    ("HG402", "hasOwner", "xsd:string"),
    ("HG403", "hasWaterProtectionZone", "xsd:string"),
    ("HG404", "hasTrafficArea", "xsd:string"),
    ("HG405", "hasGroundwaterLevel", "xsd:string"),
    ("HG406", "hasFloodArea", "xsd:string"),
    ("HG407", "hasDataStatus", "xsd:string"),
    ("HG408", "hasFloodingFrequency", "xsd:string"),
    ("HG409", "hasSoilGroup", "xsd:string"),
    ("HG003", "start_node_designation", "xsd:string"),
    ("HG004", "end_node_designation", "xsd:string"),
    ("HG006", "hasPipeSectionObjectType", "xsd:string"),
    ("HG007", "hasPipeSectionConnectingPipeStationing", "xsd:float"),
    ("HG008", "hasPipeSectionConnectingPipeStationingDirection", "xsd:string"),
    ("HG009", "hasPipeSectionConnectingPipePositioning", "xsd:integer"),
    ("HG010", "hasPipeSectionEndPointType", "xsd:string"),
    ("HG011", "hasPipeSectionPipeLineDesignation", "xsd:string"),
    ("HG012", "isChildOf", "xsd:string"),
    ("HG305", "hasPipeSectionProfileType", "xsd:string"),
    ("HG306", "hasPipeSectionProfileWidth", "xsd:integer"),
    ("HG307", "hasPipeSectionProfileHeight", "xsd:integer"),
    ("HG308", "hasPipeSectionProfileLining", "xsd:string"),
    ("HG309", "hasPipeSectionProfileLiningMaterial", "xsd:string"),
    ("HG310", "hasPipeSectionLength", "xsd:float"),
    ("HG311", "hasPipeSectionGradient", "xsd:float"),
    ("HG313", "hasPipeSectionType", "xsd:string"),
    ("HG314", "hasPipeSectionPipeLength", "xsd:float"),
    ("HG315", "hasPipeSectionStatusProfileDetail", "xsd:string"),
    ("HG316", "hasPipeSectionSelfSupportingLining", "xsd:boolean"),
    ("HG410", "hasPipeSectionWallThickness", "xsd:integer"),
    ("HG411", "hasPipeSectionBeddingType", "xsd:string"),
]

# GP fields configuration: (tag, dictionary_key, data_type)
GP_FIELDS = [
    ("GP005", "east_coordinate", "xsd:string"),
    ("GP006", "north_coordinate", "xsd:string"),
    ("GP007", "height", "xsd:float"),
    ("GP008", "positional_accuracy", "xsd:string"),
    ("GP009", "elevation_accuracy", "xsd:string"),
    ("GP010", "elevation_system", "xsd:string"),
]

# Dictionary to organize all field configurations by element type
FIELDS_CONFIG = {
    'KG': KG_FIELDS,
    'HG': HG_FIELDS,
    'GP': GP_FIELDS,
}